spring.application.name=bike-rental-api

# 1. CONEXIÓN A SUPABASE (Reemplaza con tus datos de la URI de Supabase)
spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Hm5%FRtLc2J.nsV
spring.datasource.driverClassName=org.postgresql.Driver

# 2. CONFIGURACIÓN DE JPA / HIBERNATE
# 'update' creará las tablas si no existen, pero conservará los datos siempre
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Opcional: Ver las consultas SQL en la consola para comprobar que todo fluye bien
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. CONFIGURACIÓN DEL SERVIDOR (Vital para Render)
server.port=${PORT:8080}

# 4. SEGURIDAD DE TU APP
app.security.username=admin
app.security.password=admin