spring.application.name=bike-rental-api

# ==========================
# BASE DE DATOS - SUPABASE
# ==========================
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.emvtjhxtbddohiqhvokf
spring.datasource.password=TU_NUEVA_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# JPA / HIBERNATE
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================
# SERVIDOR
# ==========================
server.port=${PORT:8080}

# ==========================
# SEGURIDAD
# ==========================
app.security.username=admin
app.security.password=admin