spring.application.name=bike-rental-api

spring.datasource.url=jdbc:postgresql://db.emvtjhxtbddohiqhvokf.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Hm5%FRtLc2J.nsV
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}

app.security.username=admin
app.security.password=admin